export { default as MediaSource } from './MediaSource';
export { default as MediaSourceFactory } from './MediaSourceFactory';
export { default as MetaDataResolver } from './MetaDataResolver';
export { default as Slide } from './Slide';
export { default as SlideDeck } from './SlideDeck';
export { default as SlideVideo } from './SlideVideo';
export { default as Timeline } from './Timeline';
export { default as Transcript } from './Transcript';
export { default as Video } from './Video';
export { default as VideoRef } from './VideoRef';
export * as Providers from './providers';
